# Migrate RDS Database
# Seed Database (only on local and dev)
# Install node_modules for server and client

# Use Procfile to start server and client
# API may be accessible via port, or may redesirect requests to Next.js

version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # upgrade AWS CLI
      # - pip install --upgrade awscli

  pre_build:
    commands:
      # install server dependencies
      - cd ./packages/commonplace-utilities/
      - npm install
      - cd ../../
      - cd ./packages/commonplace-api/
      - npm install -g ts-node typescript prisma @types/node
      - npm install
      # migrate server database
      - npx prisma migrate deploy
      - prisma generate
      - npm run db:seed
  build:
    commands:
      # install client dependencies and build static files
      - cd ./packages/commonplace-web/
      - npm install
      - npm run build
  post_build:
    commands:
      - ls -la packages/commonplace-api
      - ls -la packages/commonplace-web

artifacts:
  files:
    - "**/*"
