version: "3.4"

services:
  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - 3000:80
  api:
    build:
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
      context: ./packages/commonplace-api
    extra_hosts:
      - "localhost:192.168.0.106"
    ports:
      - "3001:3001"
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./packages/commonplace-api:/app
    environment:
      - NODE_ENV=development
      - PORT=4000
  web:
    build:
      dockerfile: Dockerfile
      context: ./packages/commonplace-web
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      # - /app/src/styles
      - ./packages/commonplace-web:/app
    environment:
      - NODE_ENV=development
