version: "3.4"

services:
  # nginx:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - 3000:80
  api:
    build:
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
      context: ./packages/commonplace-api
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
      - ./packages/commonplace-api:/app
    environment:
      - NODE_ENV=development
      - PORT=4000
  # frontend:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./frontend/web
  #   volumes:
  #     - /app/node_modules
  #     - /app/src/styles
  #     - ./frontend/web:/app
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_DEVELOPMENT_API_ENDPOINT=/devURL
