export const SeedInterests = [
  {
    title: "Food",
    items: new Set([
      "Baking",
      "Bartending",
      "Beer Tasting",
      "Breadmaking",
      "Confectionery",
      "Cooking",
      "Tea",
      "Homebrewing",
      "Recipes",
      "Wine Tasting",
      "Breakfast and Brunch",
      "Dinner",
      "Appetizers and Snacks",
      "Dessert",
      "Soup",
      "Diet",
      "World Cuisine",
      "French",
      "Chinese",
      "Italian",
      "Japanese",
      "Greek",
      "Spanish",
      "Mediterranean",
      "Lebanese",
      "Moroccan",
      "Turkish",
      "Thai",
      "Indian",
      "Cajun",
      "Mexican",
      "Caribbean",
      "German",
      "Russian",
      "Hungarian",
      "American",
    ]),
  },
  {
    title: "Art",
    items: new Set([
      "Acting",
      "Anime",
      "Ceramics",
      "Coloring",
      "Craft",
      "Crocheting",
      "Cross-Stitch",
      "Decorating",
      "Drawing",
      "Embroidery",
      "Fashion",
      "Fingerpainting",
      "Macrame",
      "Manga",
      "Miniature Art",
      "Minimalism",
      "Nail Art",
      "Origami",
      "Painting",
      "Photography",
      "Plastic Art",
      "Pottery",
      "Quilting",
      "Scrapbooking",
      "Sculpting",
      "Sketching",
      "Tapestry",
      "Diorama",
      "Whittling",
      "Rock Painting",
      "Sand Art",
    ]),
  },
  {
    title: "Sport",
    items: new Set([
      "Twirling",
      "Bowling",
      "Dance",
      "Fantasy Sports",
      "Juggling",
      "Karate",
      "Pilates",
      "Yoga",
      "Air Sports",
      "Baseball",
      "Basketball",
      "BMX",
      "Bodybuilding",
      "Canoeing",
      "Croquet",
      "Cycling",
      "Dodgeball",
      "Gymnastics",
      "Hunting",
      "Kayaking",
      "Lacrosse",
      "Longboarding",
      "Motor Sports",
      "Mountain Biking",
      "Parkour",
      "Pickleball",
      "Powerlifting",
      "Rafting",
      "Rock Climbing",
      "Roller Skating",
      "Rugby",
      "Running",
      "Sailing",
      "Shuffleboard",
      "Skateboarding",
      "Skiing",
      "Snowboarding",
      "Soccer",
      "Surfing",
      "Swimming",
      "Tennis",
      "Unicycling",
      "Water Sports",
      "Air Hockey",
      "Badminton",
      "Boxing",
      "Cheerleading",
      "Cribbage",
      "Curling",
      "Dancing",
      "Esports",
      "Fencing",
      "Hockey",
      "Ice Skating",
      "Weightlifting",
      "Wrestling",
      "Archery",
      "American Football",
      "Car Racing",
      "Cricket",
      "Disc Golf",
      "Fishing",
      "Frisbee",
      "Golfing",
      "Horseback Riding",
      "Boating",
      "Rowing",
      "Triathlon",
      "Volleyball",
    ]),
  },
  {
    title: "Music",
    items: new Set([
      "Beatboxing",
      "Karaoke",
      "Music",
      "Spoken Word",
      "Singing",
      "Blues",
      "Country",
      "Easy Listening",
      "Electronic",
      "Folk",
      "Hip hop",
      "Jazz",
      "Pop",
      "R&B",
      "Accordion",
      "Banjo",
      "Bagpipe",
      "Bass Guitar",
      "Bugle",
      "Cello",
      "Clarinet",
      "Drums",
      "Guitar",
      "Flute",
      "French Horn",
      "Piano",
      "Harmonica",
      "Harp",
      "MIDI",
      "Mandolin",
      "Marimba",
      "Oboe",
      "Saxophone",
      "Sitar",
      "Tambourine",
      "Trombone",
      "Trumpet",
      "Tuba",
      "Ukulele",
      "Vibraphone",
      "Violin",
      "Xylophone",
      "Zither",
    ]),
  },
  {
    title: "Craft",
    items: new Set([
      "3D Printing",
      "Animation",
      "Blacksmithing",
      "Restoration",
      "Candle Making",
      "Candy Making",
      "Car Building",
      "Cheesemaking",
      "Coffee Roasting",
      "Programming / Coding",
      "3D Art",
      "Digital Art",
      "DJing",
      "Drama",
      "Fashion Design",
      "Filmmaking",
      "Flower Arranging",
      "Furniture Building",
      "Furniture Design",
      "Glassblowing",
      "Graphic Design",
      "Hairstyle",
      "Inventing",
      "Jewelry Making",
      "Knitting",
      "Lace Making",
      "Lego Building",
      "Podcasting",
      "Makeup",
      "Metalworking",
      "Model Building",
      "Modeling",
      "Public Speaking",
      "Puppetry",
      "Sewing",
      "Shoemaking",
      "Soapmaking",
      "Tattooing",
      "Taxidermy",
      "Comedy",
      "Video Editing",
      "Video Making",
      "Watch Making",
      "Weaving",
      "Winemaking",
      "Woodworking",
      "Auto Detailing",
      "Beekeeping",
      "Blacksmithing",
      "Flying",
      "Videography",
      "UI Design",
      "Magic",
      "Fishkeeping",
    ]),
  },
  {
    title: "Writing",
    items: new Set([
      "Blogging",
      "Journaling",
      "Calligraphy",
      "Creative Writing",
      "Non-Fiction Writing",
      "Foreign Language",
      "Giving Advice",
      "Poetry",
      "Editing",
      "Quizzes",
      "Stories",
      "Lyrics",
    ]),
  },
  {
    title: "Games",
    items: new Set([
      "Board Games",
      "Card Games",
      "Chess",
      "Puzzles",
      "Rubik's Cube",
      "Video Games",
      "VR Games",
      "Backgammon",
      "Checkers",
      "Chess",
      "Dominoes",
      "Laser Tag",
      "Model Racing",
      "Poker",
      "Pool",
      "Ping Pong",
    ]),
  },
  {
    title: "Liesure",
    items: new Set([
      "Babysitting",
      "Cars",
      "Meditation",
      "Pet Sitting",
      "Practical Jokes",
      "Book Reading",
      "Social Media",
      "Thrifting",
      "Watching Movies",
      "Watching TV",
      "Yo-yoing",
      "Birdwatching",
      "Camping",
      "Darts",
      "Driving",
      "Hiking",
      "Kite Flying",
      "Motorcycling",
      "Safari",
      "Shopping",
      "Sledding",
      "Snorkeling",
      "Snowmobiling",
      "Tourism",
      "Travel",
      "Vacation",
      "Walking",
    ]),
  },
  {
    title: "Topic",
    items: new Set([
      "Community Activism",
      "Electronics",
      "Robots",
      "Geology",
      "Astronomy",
      "Meteorology",
      "Volunteering",
      "Archaeology",
      "Astronomy",
      "Aerospace",
      "Biology",
      "Botany",
      "Business",
      "Chemistry",
      "Entrepreneurship",
      "Geography",
      "History",
      "Linguistics",
      "Literature",
      "Mathematics",
      "Medical Science",
      "Mycology",
      "Neuroscience",
      "Philosophy",
      "Physics",
      "Psychology",
      "Sociology",
      "Sports Science",
      "Life Science",
      "Teaching",
      "Learning",
      "Microscopy",
      "Research",
      "Airplanes",
      "Meteorology",
      "Architecture",
    ]),
  },
  {
    title: "Collecting",
    items: new Set([
      "Postcards",
      "Stamps",
      "Foraging",
      "Metal Detecting",
      "Action Figures",
      "Antiquing",
      "Crystals",
      "Dolls",
      "Films",
      "Perfume",
      "Shoes",
      "Sports Memorabilia",
      "Vintage Cars",
      "Vintage Clothing",
      "Vinyl Records",
      "Fossil Hunting",
      "Leaves",
      "Metal Detecting",
      "Collecting",
    ]),
  },
  {
    title: "DIY",
    items: new Set([
      "Construction",
      "DIY",
      "Engraving",
      "Fish Farming",
      "Fish Keeping",
      "Gardening",
      "Hardware",
      "Home improvement",
      "Houseplants",
      "Hydroponics",
      "Machining",
      "Mechanics",
      "Refinishing",
      "Welding",
      "Composting",
      "Dog Training",
      "Dog Walking",
      "Farming",
      "Renovating",
    ]),
  },
  {
    title: "Action",
    items: new Set([
      "Scuba Diving",
      "Paragliding",
      "Skydiving",
      "Storm Chasing",
      "Survivalism",
    ]),
  },
];
