/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "JSONObject";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * The `JSONObject` scalar type represents JSON objects as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
     */
    json<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "JSONObject";
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    date<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  BoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  CategoryCreateNestedManyWithoutInterestsInput: { // input type
    connect?: NexusGenInputs['CategoryWhereUniqueInput'][] | null; // [CategoryWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['CategoryCreateOrConnectWithoutInterestsInput'][] | null; // [CategoryCreateOrConnectWithoutInterestsInput!]
    create?: NexusGenInputs['CategoryCreateWithoutInterestsInput'][] | null; // [CategoryCreateWithoutInterestsInput!]
  }
  CategoryCreateOrConnectWithoutInterestsInput: { // input type
    create: NexusGenInputs['CategoryCreateWithoutInterestsInput']; // CategoryCreateWithoutInterestsInput!
    where: NexusGenInputs['CategoryWhereUniqueInput']; // CategoryWhereUniqueInput!
  }
  CategoryCreateWithoutInterestsInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    generatedCategorySlug?: string | null; // String
    id?: string | null; // String
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  CategoryListRelationFilter: { // input type
    every?: NexusGenInputs['CategoryWhereInput'] | null; // CategoryWhereInput
    none?: NexusGenInputs['CategoryWhereInput'] | null; // CategoryWhereInput
    some?: NexusGenInputs['CategoryWhereInput'] | null; // CategoryWhereInput
  }
  CategoryOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  CategoryWhereInput: { // input type
    AND?: NexusGenInputs['CategoryWhereInput'][] | null; // [CategoryWhereInput!]
    NOT?: NexusGenInputs['CategoryWhereInput'][] | null; // [CategoryWhereInput!]
    OR?: NexusGenInputs['CategoryWhereInput'][] | null; // [CategoryWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    generatedCategorySlug?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    interests?: NexusGenInputs['InterestListRelationFilter'] | null; // InterestListRelationFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  CategoryWhereUniqueInput: { // input type
    generatedCategorySlug?: string | null; // String
    id?: string | null; // String
  }
  DateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  InterestCreateNestedManyWithoutModifiersInput: { // input type
    connect?: NexusGenInputs['InterestWhereUniqueInput'][] | null; // [InterestWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['InterestCreateOrConnectWithoutModifiersInput'][] | null; // [InterestCreateOrConnectWithoutModifiersInput!]
    create?: NexusGenInputs['InterestCreateWithoutModifiersInput'][] | null; // [InterestCreateWithoutModifiersInput!]
  }
  InterestCreateNestedOneWithoutPostsInput: { // input type
    connect?: NexusGenInputs['InterestWhereUniqueInput'] | null; // InterestWhereUniqueInput
    connectOrCreate?: NexusGenInputs['InterestCreateOrConnectWithoutPostsInput'] | null; // InterestCreateOrConnectWithoutPostsInput
    create?: NexusGenInputs['InterestCreateWithoutPostsInput'] | null; // InterestCreateWithoutPostsInput
  }
  InterestCreateOrConnectWithoutModifiersInput: { // input type
    create: NexusGenInputs['InterestCreateWithoutModifiersInput']; // InterestCreateWithoutModifiersInput!
    where: NexusGenInputs['InterestWhereUniqueInput']; // InterestWhereUniqueInput!
  }
  InterestCreateOrConnectWithoutPostsInput: { // input type
    create: NexusGenInputs['InterestCreateWithoutPostsInput']; // InterestCreateWithoutPostsInput!
    where: NexusGenInputs['InterestWhereUniqueInput']; // InterestWhereUniqueInput!
  }
  InterestCreateWithoutModifiersInput: { // input type
    categories?: NexusGenInputs['CategoryCreateNestedManyWithoutInterestsInput'] | null; // CategoryCreateNestedManyWithoutInterestsInput
    contentType: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    generatedInterestSlug?: string | null; // String
    id?: string | null; // String
    name: string; // String!
    posts?: NexusGenInputs['PostCreateNestedManyWithoutInterestInput'] | null; // PostCreateNestedManyWithoutInterestInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  InterestCreateWithoutPostsInput: { // input type
    categories?: NexusGenInputs['CategoryCreateNestedManyWithoutInterestsInput'] | null; // CategoryCreateNestedManyWithoutInterestsInput
    contentType: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    generatedInterestSlug?: string | null; // String
    id?: string | null; // String
    modifiers?: NexusGenInputs['ModifierCreateNestedManyWithoutInterestsInput'] | null; // ModifierCreateNestedManyWithoutInterestsInput
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  InterestListRelationFilter: { // input type
    every?: NexusGenInputs['InterestWhereInput'] | null; // InterestWhereInput
    none?: NexusGenInputs['InterestWhereInput'] | null; // InterestWhereInput
    some?: NexusGenInputs['InterestWhereInput'] | null; // InterestWhereInput
  }
  InterestOrderByWithRelationInput: { // input type
    categories?: NexusGenInputs['CategoryOrderByRelationAggregateInput'] | null; // CategoryOrderByRelationAggregateInput
    contentType?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    generatedInterestSlug?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    modifiers?: NexusGenInputs['ModifierOrderByRelationAggregateInput'] | null; // ModifierOrderByRelationAggregateInput
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    posts?: NexusGenInputs['PostOrderByRelationAggregateInput'] | null; // PostOrderByRelationAggregateInput
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  InterestWhereInput: { // input type
    AND?: NexusGenInputs['InterestWhereInput'][] | null; // [InterestWhereInput!]
    NOT?: NexusGenInputs['InterestWhereInput'][] | null; // [InterestWhereInput!]
    OR?: NexusGenInputs['InterestWhereInput'][] | null; // [InterestWhereInput!]
    categories?: NexusGenInputs['CategoryListRelationFilter'] | null; // CategoryListRelationFilter
    contentType?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    generatedInterestSlug?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    modifiers?: NexusGenInputs['ModifierListRelationFilter'] | null; // ModifierListRelationFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    posts?: NexusGenInputs['PostListRelationFilter'] | null; // PostListRelationFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  InterestWhereUniqueInput: { // input type
    generatedInterestSlug?: string | null; // String
    id?: string | null; // String
  }
  MessageCreateManyPostInput: { // input type
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    threadId: string; // String!
    type: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    userId: string; // String!
  }
  MessageCreateManyPostInputEnvelope: { // input type
    data?: NexusGenInputs['MessageCreateManyPostInput'][] | null; // [MessageCreateManyPostInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  MessageCreateManyThreadInput: { // input type
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    postId?: string | null; // String
    type: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    userId: string; // String!
  }
  MessageCreateManyThreadInputEnvelope: { // input type
    data?: NexusGenInputs['MessageCreateManyThreadInput'][] | null; // [MessageCreateManyThreadInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  MessageCreateManyUserInput: { // input type
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    postId?: string | null; // String
    threadId: string; // String!
    type: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  MessageCreateManyUserInputEnvelope: { // input type
    data?: NexusGenInputs['MessageCreateManyUserInput'][] | null; // [MessageCreateManyUserInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  MessageCreateNestedManyWithoutPostInput: { // input type
    connect?: NexusGenInputs['MessageWhereUniqueInput'][] | null; // [MessageWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['MessageCreateOrConnectWithoutPostInput'][] | null; // [MessageCreateOrConnectWithoutPostInput!]
    create?: NexusGenInputs['MessageCreateWithoutPostInput'][] | null; // [MessageCreateWithoutPostInput!]
    createMany?: NexusGenInputs['MessageCreateManyPostInputEnvelope'] | null; // MessageCreateManyPostInputEnvelope
  }
  MessageCreateNestedManyWithoutThreadInput: { // input type
    connect?: NexusGenInputs['MessageWhereUniqueInput'][] | null; // [MessageWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['MessageCreateOrConnectWithoutThreadInput'][] | null; // [MessageCreateOrConnectWithoutThreadInput!]
    create?: NexusGenInputs['MessageCreateWithoutThreadInput'][] | null; // [MessageCreateWithoutThreadInput!]
    createMany?: NexusGenInputs['MessageCreateManyThreadInputEnvelope'] | null; // MessageCreateManyThreadInputEnvelope
  }
  MessageCreateNestedManyWithoutUserInput: { // input type
    connect?: NexusGenInputs['MessageWhereUniqueInput'][] | null; // [MessageWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['MessageCreateOrConnectWithoutUserInput'][] | null; // [MessageCreateOrConnectWithoutUserInput!]
    create?: NexusGenInputs['MessageCreateWithoutUserInput'][] | null; // [MessageCreateWithoutUserInput!]
    createMany?: NexusGenInputs['MessageCreateManyUserInputEnvelope'] | null; // MessageCreateManyUserInputEnvelope
  }
  MessageCreateOrConnectWithoutPostInput: { // input type
    create: NexusGenInputs['MessageCreateWithoutPostInput']; // MessageCreateWithoutPostInput!
    where: NexusGenInputs['MessageWhereUniqueInput']; // MessageWhereUniqueInput!
  }
  MessageCreateOrConnectWithoutThreadInput: { // input type
    create: NexusGenInputs['MessageCreateWithoutThreadInput']; // MessageCreateWithoutThreadInput!
    where: NexusGenInputs['MessageWhereUniqueInput']; // MessageWhereUniqueInput!
  }
  MessageCreateOrConnectWithoutUserInput: { // input type
    create: NexusGenInputs['MessageCreateWithoutUserInput']; // MessageCreateWithoutUserInput!
    where: NexusGenInputs['MessageWhereUniqueInput']; // MessageWhereUniqueInput!
  }
  MessageCreateWithoutPostInput: { // input type
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    thread: NexusGenInputs['ThreadCreateNestedOneWithoutMessagesInput']; // ThreadCreateNestedOneWithoutMessagesInput!
    type: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    user: NexusGenInputs['UserCreateNestedOneWithoutMessagesInput']; // UserCreateNestedOneWithoutMessagesInput!
  }
  MessageCreateWithoutThreadInput: { // input type
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    post?: NexusGenInputs['PostCreateNestedOneWithoutMessagesInput'] | null; // PostCreateNestedOneWithoutMessagesInput
    type: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    user: NexusGenInputs['UserCreateNestedOneWithoutMessagesInput']; // UserCreateNestedOneWithoutMessagesInput!
  }
  MessageCreateWithoutUserInput: { // input type
    content: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    post?: NexusGenInputs['PostCreateNestedOneWithoutMessagesInput'] | null; // PostCreateNestedOneWithoutMessagesInput
    thread: NexusGenInputs['ThreadCreateNestedOneWithoutMessagesInput']; // ThreadCreateNestedOneWithoutMessagesInput!
    type: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  MessageListRelationFilter: { // input type
    every?: NexusGenInputs['MessageWhereInput'] | null; // MessageWhereInput
    none?: NexusGenInputs['MessageWhereInput'] | null; // MessageWhereInput
    some?: NexusGenInputs['MessageWhereInput'] | null; // MessageWhereInput
  }
  MessageOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  MessageOrderByWithRelationInput: { // input type
    content?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    post?: NexusGenInputs['PostOrderByWithRelationInput'] | null; // PostOrderByWithRelationInput
    postId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    thread?: NexusGenInputs['ThreadOrderByWithRelationInput'] | null; // ThreadOrderByWithRelationInput
    threadId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    type?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    user?: NexusGenInputs['UserOrderByWithRelationInput'] | null; // UserOrderByWithRelationInput
    userId?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  MessageWhereInput: { // input type
    AND?: NexusGenInputs['MessageWhereInput'][] | null; // [MessageWhereInput!]
    NOT?: NexusGenInputs['MessageWhereInput'][] | null; // [MessageWhereInput!]
    OR?: NexusGenInputs['MessageWhereInput'][] | null; // [MessageWhereInput!]
    content?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    post?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    postId?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    thread?: NexusGenInputs['ThreadWhereInput'] | null; // ThreadWhereInput
    threadId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    type?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    user?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    userId?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  MessageWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  ModifierCreateNestedManyWithoutInterestsInput: { // input type
    connect?: NexusGenInputs['ModifierWhereUniqueInput'][] | null; // [ModifierWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['ModifierCreateOrConnectWithoutInterestsInput'][] | null; // [ModifierCreateOrConnectWithoutInterestsInput!]
    create?: NexusGenInputs['ModifierCreateWithoutInterestsInput'][] | null; // [ModifierCreateWithoutInterestsInput!]
  }
  ModifierCreateNestedManyWithoutPostsInput: { // input type
    connect?: NexusGenInputs['ModifierWhereUniqueInput'][] | null; // [ModifierWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['ModifierCreateOrConnectWithoutPostsInput'][] | null; // [ModifierCreateOrConnectWithoutPostsInput!]
    create?: NexusGenInputs['ModifierCreateWithoutPostsInput'][] | null; // [ModifierCreateWithoutPostsInput!]
  }
  ModifierCreateOrConnectWithoutInterestsInput: { // input type
    create: NexusGenInputs['ModifierCreateWithoutInterestsInput']; // ModifierCreateWithoutInterestsInput!
    where: NexusGenInputs['ModifierWhereUniqueInput']; // ModifierWhereUniqueInput!
  }
  ModifierCreateOrConnectWithoutPostsInput: { // input type
    create: NexusGenInputs['ModifierCreateWithoutPostsInput']; // ModifierCreateWithoutPostsInput!
    where: NexusGenInputs['ModifierWhereUniqueInput']; // ModifierWhereUniqueInput!
  }
  ModifierCreateWithoutInterestsInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    generatedModifierSlug?: string | null; // String
    id?: string | null; // String
    name: string; // String!
    posts?: NexusGenInputs['PostCreateNestedManyWithoutModifiersInput'] | null; // PostCreateNestedManyWithoutModifiersInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ModifierCreateWithoutPostsInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    generatedModifierSlug?: string | null; // String
    id?: string | null; // String
    interests?: NexusGenInputs['InterestCreateNestedManyWithoutModifiersInput'] | null; // InterestCreateNestedManyWithoutModifiersInput
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ModifierListRelationFilter: { // input type
    every?: NexusGenInputs['ModifierWhereInput'] | null; // ModifierWhereInput
    none?: NexusGenInputs['ModifierWhereInput'] | null; // ModifierWhereInput
    some?: NexusGenInputs['ModifierWhereInput'] | null; // ModifierWhereInput
  }
  ModifierOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  ModifierWhereInput: { // input type
    AND?: NexusGenInputs['ModifierWhereInput'][] | null; // [ModifierWhereInput!]
    NOT?: NexusGenInputs['ModifierWhereInput'][] | null; // [ModifierWhereInput!]
    OR?: NexusGenInputs['ModifierWhereInput'][] | null; // [ModifierWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    generatedModifierSlug?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    interests?: NexusGenInputs['InterestListRelationFilter'] | null; // InterestListRelationFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    posts?: NexusGenInputs['PostListRelationFilter'] | null; // PostListRelationFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  ModifierWhereUniqueInput: { // input type
    generatedModifierSlug?: string | null; // String
    id?: string | null; // String
  }
  NestedBoolFilter: { // input type
    equals?: boolean | null; // Boolean
    not?: NexusGenInputs['NestedBoolFilter'] | null; // NestedBoolFilter
  }
  NestedDateTimeFilter: { // input type
    equals?: NexusGenScalars['DateTime'] | null; // DateTime
    gt?: NexusGenScalars['DateTime'] | null; // DateTime
    gte?: NexusGenScalars['DateTime'] | null; // DateTime
    in?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
    lt?: NexusGenScalars['DateTime'] | null; // DateTime
    lte?: NexusGenScalars['DateTime'] | null; // DateTime
    not?: NexusGenInputs['NestedDateTimeFilter'] | null; // NestedDateTimeFilter
    notIn?: NexusGenScalars['DateTime'][] | null; // [DateTime!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  PostCreateManyCreatorInput: { // input type
    content: string; // String!
    contentPreview: string; // String!
    contentType: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description: string; // String!
    generatedTitleSlug?: string | null; // String
    id?: string | null; // String
    interestId: string; // String!
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostCreateManyCreatorInputEnvelope: { // input type
    data?: NexusGenInputs['PostCreateManyCreatorInput'][] | null; // [PostCreateManyCreatorInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  PostCreateManyInterestInput: { // input type
    content: string; // String!
    contentPreview: string; // String!
    contentType: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    creatorId: string; // String!
    description: string; // String!
    generatedTitleSlug?: string | null; // String
    id?: string | null; // String
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostCreateManyInterestInputEnvelope: { // input type
    data?: NexusGenInputs['PostCreateManyInterestInput'][] | null; // [PostCreateManyInterestInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  PostCreateNestedManyWithoutCreatorInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutCreatorInput'][] | null; // [PostCreateOrConnectWithoutCreatorInput!]
    create?: NexusGenInputs['PostCreateWithoutCreatorInput'][] | null; // [PostCreateWithoutCreatorInput!]
    createMany?: NexusGenInputs['PostCreateManyCreatorInputEnvelope'] | null; // PostCreateManyCreatorInputEnvelope
  }
  PostCreateNestedManyWithoutInterestInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutInterestInput'][] | null; // [PostCreateOrConnectWithoutInterestInput!]
    create?: NexusGenInputs['PostCreateWithoutInterestInput'][] | null; // [PostCreateWithoutInterestInput!]
    createMany?: NexusGenInputs['PostCreateManyInterestInputEnvelope'] | null; // PostCreateManyInterestInputEnvelope
  }
  PostCreateNestedManyWithoutModifiersInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'][] | null; // [PostWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutModifiersInput'][] | null; // [PostCreateOrConnectWithoutModifiersInput!]
    create?: NexusGenInputs['PostCreateWithoutModifiersInput'][] | null; // [PostCreateWithoutModifiersInput!]
  }
  PostCreateNestedOneWithoutMessagesInput: { // input type
    connect?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
    connectOrCreate?: NexusGenInputs['PostCreateOrConnectWithoutMessagesInput'] | null; // PostCreateOrConnectWithoutMessagesInput
    create?: NexusGenInputs['PostCreateWithoutMessagesInput'] | null; // PostCreateWithoutMessagesInput
  }
  PostCreateOrConnectWithoutCreatorInput: { // input type
    create: NexusGenInputs['PostCreateWithoutCreatorInput']; // PostCreateWithoutCreatorInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateOrConnectWithoutInterestInput: { // input type
    create: NexusGenInputs['PostCreateWithoutInterestInput']; // PostCreateWithoutInterestInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateOrConnectWithoutMessagesInput: { // input type
    create: NexusGenInputs['PostCreateWithoutMessagesInput']; // PostCreateWithoutMessagesInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateOrConnectWithoutModifiersInput: { // input type
    create: NexusGenInputs['PostCreateWithoutModifiersInput']; // PostCreateWithoutModifiersInput!
    where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
  }
  PostCreateWithoutCreatorInput: { // input type
    content: string; // String!
    contentPreview: string; // String!
    contentType: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description: string; // String!
    generatedTitleSlug?: string | null; // String
    id?: string | null; // String
    interest: NexusGenInputs['InterestCreateNestedOneWithoutPostsInput']; // InterestCreateNestedOneWithoutPostsInput!
    messages?: NexusGenInputs['MessageCreateNestedManyWithoutPostInput'] | null; // MessageCreateNestedManyWithoutPostInput
    modifiers?: NexusGenInputs['ModifierCreateNestedManyWithoutPostsInput'] | null; // ModifierCreateNestedManyWithoutPostsInput
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostCreateWithoutInterestInput: { // input type
    content: string; // String!
    contentPreview: string; // String!
    contentType: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    creator: NexusGenInputs['UserCreateNestedOneWithoutPostsInput']; // UserCreateNestedOneWithoutPostsInput!
    description: string; // String!
    generatedTitleSlug?: string | null; // String
    id?: string | null; // String
    messages?: NexusGenInputs['MessageCreateNestedManyWithoutPostInput'] | null; // MessageCreateNestedManyWithoutPostInput
    modifiers?: NexusGenInputs['ModifierCreateNestedManyWithoutPostsInput'] | null; // ModifierCreateNestedManyWithoutPostsInput
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostCreateWithoutMessagesInput: { // input type
    content: string; // String!
    contentPreview: string; // String!
    contentType: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    creator: NexusGenInputs['UserCreateNestedOneWithoutPostsInput']; // UserCreateNestedOneWithoutPostsInput!
    description: string; // String!
    generatedTitleSlug?: string | null; // String
    id?: string | null; // String
    interest: NexusGenInputs['InterestCreateNestedOneWithoutPostsInput']; // InterestCreateNestedOneWithoutPostsInput!
    modifiers?: NexusGenInputs['ModifierCreateNestedManyWithoutPostsInput'] | null; // ModifierCreateNestedManyWithoutPostsInput
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostCreateWithoutModifiersInput: { // input type
    content: string; // String!
    contentPreview: string; // String!
    contentType: string; // String!
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    creator: NexusGenInputs['UserCreateNestedOneWithoutPostsInput']; // UserCreateNestedOneWithoutPostsInput!
    description: string; // String!
    generatedTitleSlug?: string | null; // String
    id?: string | null; // String
    interest: NexusGenInputs['InterestCreateNestedOneWithoutPostsInput']; // InterestCreateNestedOneWithoutPostsInput!
    messages?: NexusGenInputs['MessageCreateNestedManyWithoutPostInput'] | null; // MessageCreateNestedManyWithoutPostInput
    title: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PostListRelationFilter: { // input type
    every?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    none?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    some?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
  }
  PostOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  PostOrderByWithRelationInput: { // input type
    content?: NexusGenEnums['SortOrder'] | null; // SortOrder
    contentPreview?: NexusGenEnums['SortOrder'] | null; // SortOrder
    contentType?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    creator?: NexusGenInputs['UserOrderByWithRelationInput'] | null; // UserOrderByWithRelationInput
    creatorId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    description?: NexusGenEnums['SortOrder'] | null; // SortOrder
    generatedTitleSlug?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    interest?: NexusGenInputs['InterestOrderByWithRelationInput'] | null; // InterestOrderByWithRelationInput
    interestId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    messages?: NexusGenInputs['MessageOrderByRelationAggregateInput'] | null; // MessageOrderByRelationAggregateInput
    modifiers?: NexusGenInputs['ModifierOrderByRelationAggregateInput'] | null; // ModifierOrderByRelationAggregateInput
    title?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  PostWhereInput: { // input type
    AND?: NexusGenInputs['PostWhereInput'][] | null; // [PostWhereInput!]
    NOT?: NexusGenInputs['PostWhereInput'][] | null; // [PostWhereInput!]
    OR?: NexusGenInputs['PostWhereInput'][] | null; // [PostWhereInput!]
    content?: NexusGenInputs['StringFilter'] | null; // StringFilter
    contentPreview?: NexusGenInputs['StringFilter'] | null; // StringFilter
    contentType?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    creator?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    creatorId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    description?: NexusGenInputs['StringFilter'] | null; // StringFilter
    generatedTitleSlug?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    interest?: NexusGenInputs['InterestWhereInput'] | null; // InterestWhereInput
    interestId?: NexusGenInputs['StringFilter'] | null; // StringFilter
    messages?: NexusGenInputs['MessageListRelationFilter'] | null; // MessageListRelationFilter
    modifiers?: NexusGenInputs['ModifierListRelationFilter'] | null; // ModifierListRelationFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  PostWhereUniqueInput: { // input type
    generatedTitleSlug?: string | null; // String
    id?: string | null; // String
  }
  RecordCreateInput: { // input type
    content?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    name: string; // String!
    thread?: NexusGenInputs['ThreadCreateNestedOneWithoutReadHistoryInput'] | null; // ThreadCreateNestedOneWithoutReadHistoryInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  RecordCreateManyThreadInput: { // input type
    content?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  RecordCreateManyThreadInputEnvelope: { // input type
    data?: NexusGenInputs['RecordCreateManyThreadInput'][] | null; // [RecordCreateManyThreadInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  RecordCreateNestedManyWithoutThreadInput: { // input type
    connect?: NexusGenInputs['RecordWhereUniqueInput'][] | null; // [RecordWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['RecordCreateOrConnectWithoutThreadInput'][] | null; // [RecordCreateOrConnectWithoutThreadInput!]
    create?: NexusGenInputs['RecordCreateWithoutThreadInput'][] | null; // [RecordCreateWithoutThreadInput!]
    createMany?: NexusGenInputs['RecordCreateManyThreadInputEnvelope'] | null; // RecordCreateManyThreadInputEnvelope
  }
  RecordCreateOrConnectWithoutThreadInput: { // input type
    create: NexusGenInputs['RecordCreateWithoutThreadInput']; // RecordCreateWithoutThreadInput!
    where: NexusGenInputs['RecordWhereUniqueInput']; // RecordWhereUniqueInput!
  }
  RecordCreateWithoutThreadInput: { // input type
    content?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    name: string; // String!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  RecordListRelationFilter: { // input type
    every?: NexusGenInputs['RecordWhereInput'] | null; // RecordWhereInput
    none?: NexusGenInputs['RecordWhereInput'] | null; // RecordWhereInput
    some?: NexusGenInputs['RecordWhereInput'] | null; // RecordWhereInput
  }
  RecordOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  RecordOrderByWithRelationInput: { // input type
    content?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    thread?: NexusGenInputs['ThreadOrderByWithRelationInput'] | null; // ThreadOrderByWithRelationInput
    threadId?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  RecordWhereInput: { // input type
    AND?: NexusGenInputs['RecordWhereInput'][] | null; // [RecordWhereInput!]
    NOT?: NexusGenInputs['RecordWhereInput'][] | null; // [RecordWhereInput!]
    OR?: NexusGenInputs['RecordWhereInput'][] | null; // [RecordWhereInput!]
    content?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    thread?: NexusGenInputs['ThreadWhereInput'] | null; // ThreadWhereInput
    threadId?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  RecordWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  ThreadCreateNestedManyWithoutUsersInput: { // input type
    connect?: NexusGenInputs['ThreadWhereUniqueInput'][] | null; // [ThreadWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['ThreadCreateOrConnectWithoutUsersInput'][] | null; // [ThreadCreateOrConnectWithoutUsersInput!]
    create?: NexusGenInputs['ThreadCreateWithoutUsersInput'][] | null; // [ThreadCreateWithoutUsersInput!]
  }
  ThreadCreateNestedOneWithoutMessagesInput: { // input type
    connect?: NexusGenInputs['ThreadWhereUniqueInput'] | null; // ThreadWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ThreadCreateOrConnectWithoutMessagesInput'] | null; // ThreadCreateOrConnectWithoutMessagesInput
    create?: NexusGenInputs['ThreadCreateWithoutMessagesInput'] | null; // ThreadCreateWithoutMessagesInput
  }
  ThreadCreateNestedOneWithoutReadHistoryInput: { // input type
    connect?: NexusGenInputs['ThreadWhereUniqueInput'] | null; // ThreadWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ThreadCreateOrConnectWithoutReadHistoryInput'] | null; // ThreadCreateOrConnectWithoutReadHistoryInput
    create?: NexusGenInputs['ThreadCreateWithoutReadHistoryInput'] | null; // ThreadCreateWithoutReadHistoryInput
  }
  ThreadCreateOrConnectWithoutMessagesInput: { // input type
    create: NexusGenInputs['ThreadCreateWithoutMessagesInput']; // ThreadCreateWithoutMessagesInput!
    where: NexusGenInputs['ThreadWhereUniqueInput']; // ThreadWhereUniqueInput!
  }
  ThreadCreateOrConnectWithoutReadHistoryInput: { // input type
    create: NexusGenInputs['ThreadCreateWithoutReadHistoryInput']; // ThreadCreateWithoutReadHistoryInput!
    where: NexusGenInputs['ThreadWhereUniqueInput']; // ThreadWhereUniqueInput!
  }
  ThreadCreateOrConnectWithoutUsersInput: { // input type
    create: NexusGenInputs['ThreadCreateWithoutUsersInput']; // ThreadCreateWithoutUsersInput!
    where: NexusGenInputs['ThreadWhereUniqueInput']; // ThreadWhereUniqueInput!
  }
  ThreadCreateWithoutMessagesInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    readHistory?: NexusGenInputs['RecordCreateNestedManyWithoutThreadInput'] | null; // RecordCreateNestedManyWithoutThreadInput
    repliesAllowed: boolean; // Boolean!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    users?: NexusGenInputs['UserCreateNestedManyWithoutThreadsInput'] | null; // UserCreateNestedManyWithoutThreadsInput
  }
  ThreadCreateWithoutReadHistoryInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    messages?: NexusGenInputs['MessageCreateNestedManyWithoutThreadInput'] | null; // MessageCreateNestedManyWithoutThreadInput
    repliesAllowed: boolean; // Boolean!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
    users?: NexusGenInputs['UserCreateNestedManyWithoutThreadsInput'] | null; // UserCreateNestedManyWithoutThreadsInput
  }
  ThreadCreateWithoutUsersInput: { // input type
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    id?: string | null; // String
    messages?: NexusGenInputs['MessageCreateNestedManyWithoutThreadInput'] | null; // MessageCreateNestedManyWithoutThreadInput
    readHistory?: NexusGenInputs['RecordCreateNestedManyWithoutThreadInput'] | null; // RecordCreateNestedManyWithoutThreadInput
    repliesAllowed: boolean; // Boolean!
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  ThreadListRelationFilter: { // input type
    every?: NexusGenInputs['ThreadWhereInput'] | null; // ThreadWhereInput
    none?: NexusGenInputs['ThreadWhereInput'] | null; // ThreadWhereInput
    some?: NexusGenInputs['ThreadWhereInput'] | null; // ThreadWhereInput
  }
  ThreadOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  ThreadOrderByWithRelationInput: { // input type
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    messages?: NexusGenInputs['MessageOrderByRelationAggregateInput'] | null; // MessageOrderByRelationAggregateInput
    readHistory?: NexusGenInputs['RecordOrderByRelationAggregateInput'] | null; // RecordOrderByRelationAggregateInput
    repliesAllowed?: NexusGenEnums['SortOrder'] | null; // SortOrder
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    users?: NexusGenInputs['UserOrderByRelationAggregateInput'] | null; // UserOrderByRelationAggregateInput
  }
  ThreadWhereInput: { // input type
    AND?: NexusGenInputs['ThreadWhereInput'][] | null; // [ThreadWhereInput!]
    NOT?: NexusGenInputs['ThreadWhereInput'][] | null; // [ThreadWhereInput!]
    OR?: NexusGenInputs['ThreadWhereInput'][] | null; // [ThreadWhereInput!]
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    messages?: NexusGenInputs['MessageListRelationFilter'] | null; // MessageListRelationFilter
    readHistory?: NexusGenInputs['RecordListRelationFilter'] | null; // RecordListRelationFilter
    repliesAllowed?: NexusGenInputs['BoolFilter'] | null; // BoolFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    users?: NexusGenInputs['UserListRelationFilter'] | null; // UserListRelationFilter
  }
  ThreadWhereUniqueInput: { // input type
    id?: string | null; // String
  }
  UserCreateNestedManyWithoutThreadsInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'][] | null; // [UserWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutThreadsInput'][] | null; // [UserCreateOrConnectWithoutThreadsInput!]
    create?: NexusGenInputs['UserCreateWithoutThreadsInput'][] | null; // [UserCreateWithoutThreadsInput!]
  }
  UserCreateNestedOneWithoutMessagesInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutMessagesInput'] | null; // UserCreateOrConnectWithoutMessagesInput
    create?: NexusGenInputs['UserCreateWithoutMessagesInput'] | null; // UserCreateWithoutMessagesInput
  }
  UserCreateNestedOneWithoutPostsInput: { // input type
    connect?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
    connectOrCreate?: NexusGenInputs['UserCreateOrConnectWithoutPostsInput'] | null; // UserCreateOrConnectWithoutPostsInput
    create?: NexusGenInputs['UserCreateWithoutPostsInput'] | null; // UserCreateWithoutPostsInput
  }
  UserCreateOrConnectWithoutMessagesInput: { // input type
    create: NexusGenInputs['UserCreateWithoutMessagesInput']; // UserCreateWithoutMessagesInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateOrConnectWithoutPostsInput: { // input type
    create: NexusGenInputs['UserCreateWithoutPostsInput']; // UserCreateWithoutPostsInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateOrConnectWithoutThreadsInput: { // input type
    create: NexusGenInputs['UserCreateWithoutThreadsInput']; // UserCreateWithoutThreadsInput!
    where: NexusGenInputs['UserWhereUniqueInput']; // UserWhereUniqueInput!
  }
  UserCreateWithoutMessagesInput: { // input type
    chosenUsername?: string | null; // String
    coverImage?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    credit?: number | null; // Int
    email: string; // String!
    generatedUsername?: string | null; // String
    id?: string | null; // String
    name?: string | null; // String
    password: string; // String!
    posts?: NexusGenInputs['PostCreateNestedManyWithoutCreatorInput'] | null; // PostCreateNestedManyWithoutCreatorInput
    profileImage?: string | null; // String
    threads?: NexusGenInputs['ThreadCreateNestedManyWithoutUsersInput'] | null; // ThreadCreateNestedManyWithoutUsersInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserCreateWithoutPostsInput: { // input type
    chosenUsername?: string | null; // String
    coverImage?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    credit?: number | null; // Int
    email: string; // String!
    generatedUsername?: string | null; // String
    id?: string | null; // String
    messages?: NexusGenInputs['MessageCreateNestedManyWithoutUserInput'] | null; // MessageCreateNestedManyWithoutUserInput
    name?: string | null; // String
    password: string; // String!
    profileImage?: string | null; // String
    threads?: NexusGenInputs['ThreadCreateNestedManyWithoutUsersInput'] | null; // ThreadCreateNestedManyWithoutUsersInput
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserCreateWithoutThreadsInput: { // input type
    chosenUsername?: string | null; // String
    coverImage?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    credit?: number | null; // Int
    email: string; // String!
    generatedUsername?: string | null; // String
    id?: string | null; // String
    messages?: NexusGenInputs['MessageCreateNestedManyWithoutUserInput'] | null; // MessageCreateNestedManyWithoutUserInput
    name?: string | null; // String
    password: string; // String!
    posts?: NexusGenInputs['PostCreateNestedManyWithoutCreatorInput'] | null; // PostCreateNestedManyWithoutCreatorInput
    profileImage?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  UserListRelationFilter: { // input type
    every?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    none?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
    some?: NexusGenInputs['UserWhereInput'] | null; // UserWhereInput
  }
  UserOrderByRelationAggregateInput: { // input type
    _count?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserOrderByWithRelationInput: { // input type
    chosenUsername?: NexusGenEnums['SortOrder'] | null; // SortOrder
    coverImage?: NexusGenEnums['SortOrder'] | null; // SortOrder
    createdAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
    credit?: NexusGenEnums['SortOrder'] | null; // SortOrder
    email?: NexusGenEnums['SortOrder'] | null; // SortOrder
    generatedUsername?: NexusGenEnums['SortOrder'] | null; // SortOrder
    id?: NexusGenEnums['SortOrder'] | null; // SortOrder
    messages?: NexusGenInputs['MessageOrderByRelationAggregateInput'] | null; // MessageOrderByRelationAggregateInput
    name?: NexusGenEnums['SortOrder'] | null; // SortOrder
    password?: NexusGenEnums['SortOrder'] | null; // SortOrder
    posts?: NexusGenInputs['PostOrderByRelationAggregateInput'] | null; // PostOrderByRelationAggregateInput
    profileImage?: NexusGenEnums['SortOrder'] | null; // SortOrder
    threads?: NexusGenInputs['ThreadOrderByRelationAggregateInput'] | null; // ThreadOrderByRelationAggregateInput
    updatedAt?: NexusGenEnums['SortOrder'] | null; // SortOrder
  }
  UserWhereInput: { // input type
    AND?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    NOT?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    OR?: NexusGenInputs['UserWhereInput'][] | null; // [UserWhereInput!]
    chosenUsername?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    coverImage?: NexusGenInputs['StringFilter'] | null; // StringFilter
    createdAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
    credit?: NexusGenInputs['IntFilter'] | null; // IntFilter
    email?: NexusGenInputs['StringFilter'] | null; // StringFilter
    generatedUsername?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['StringFilter'] | null; // StringFilter
    messages?: NexusGenInputs['MessageListRelationFilter'] | null; // MessageListRelationFilter
    name?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    password?: NexusGenInputs['StringFilter'] | null; // StringFilter
    posts?: NexusGenInputs['PostListRelationFilter'] | null; // PostListRelationFilter
    profileImage?: NexusGenInputs['StringFilter'] | null; // StringFilter
    threads?: NexusGenInputs['ThreadListRelationFilter'] | null; // ThreadListRelationFilter
    updatedAt?: NexusGenInputs['DateTimeFilter'] | null; // DateTimeFilter
  }
  UserWhereUniqueInput: { // input type
    chosenUsername?: string | null; // String
    email?: string | null; // String
    generatedUsername?: string | null; // String
    id?: string | null; // String
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
  SortOrder: "asc" | "desc"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
  JSONObject: any
  Upload: any
}

export interface NexusGenObjects {
  Category: { // root type
    id: string; // String!
    name: string; // String!
  }
  Interest: { // root type
    generatedInterestSlug: string; // String!
    id: string; // String!
    name: string; // String!
  }
  Message: { // root type
    content: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    type: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Mutation: {};
  Post: { // root type
    content: string; // String!
    contentPreview: string; // String!
    contentType: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string; // String!
    generatedTitleSlug: string; // String!
    id: string; // String!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  PublicPost: { // root type
    content?: string | null; // String
    contentPreview?: string | null; // String
    contentType?: string | null; // String
    createdAt?: NexusGenScalars['DateTime'] | null; // DateTime
    description?: string | null; // String
    generatedTitleSlug?: string | null; // String
    id?: string | null; // String
    interest?: NexusGenRootTypes['Interest'] | null; // Interest
    title?: string | null; // String
    updatedAt?: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PublicUser: { // root type
    chosenUsername?: string | null; // String
    coverImage?: string | null; // String
    generatedUsername?: string | null; // String
    name?: string | null; // String
    profileImage?: string | null; // String
  }
  Query: {};
  Record: { // root type
    content?: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    name: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Thread: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    repliesAllowed: boolean; // Boolean!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  User: { // root type
    chosenUsername?: string | null; // String
    coverImage: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    credit: number; // Int!
    email: string; // String!
    generatedUsername: string; // String!
    name?: string | null; // String
    profileImage: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Category: { // field return type
    id: string; // String!
    interests: NexusGenRootTypes['Interest'][]; // [Interest!]!
    name: string; // String!
  }
  Interest: { // field return type
    categories: NexusGenRootTypes['Category'][]; // [Category!]!
    generatedInterestSlug: string; // String!
    id: string; // String!
    name: string; // String!
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
  }
  Message: { // field return type
    content: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    post: NexusGenRootTypes['Post'] | null; // Post
    type: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    user: NexusGenRootTypes['User']; // User!
  }
  Mutation: { // field return type
    createMessage: NexusGenRootTypes['Message']; // Message!
    createOneRecord: NexusGenRootTypes['Record']; // Record!
    createPost: NexusGenRootTypes['Post']; // Post!
    deletePost: string; // String!
    updatePost: NexusGenRootTypes['Post']; // Post!
    updateProfile: string; // String!
  }
  Post: { // field return type
    content: string; // String!
    contentPreview: string; // String!
    contentType: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    creator: NexusGenRootTypes['User']; // User!
    description: string; // String!
    generatedTitleSlug: string; // String!
    id: string; // String!
    interest: NexusGenRootTypes['Interest']; // Interest!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  PublicPost: { // field return type
    content: string | null; // String
    contentPreview: string | null; // String
    contentType: string | null; // String
    createdAt: NexusGenScalars['DateTime'] | null; // DateTime
    description: string | null; // String
    generatedTitleSlug: string | null; // String
    id: string | null; // String
    interest: NexusGenRootTypes['Interest'] | null; // Interest
    title: string | null; // String
    updatedAt: NexusGenScalars['DateTime'] | null; // DateTime
  }
  PublicUser: { // field return type
    chosenUsername: string | null; // String
    coverImage: string | null; // String
    generatedUsername: string | null; // String
    name: string | null; // String
    profileImage: string | null; // String
  }
  Query: { // field return type
    authenticate: string; // String!
    categories: NexusGenRootTypes['Category'][]; // [Category!]!
    getPostByPostTitle: NexusGenRootTypes['PublicPost'] | null; // PublicPost
    getPostImpressions: Array<NexusGenRootTypes['Message'] | null>; // [Message]!
    getPostURLs: Array<string | null> | null; // [String]
    getPostsByUsername: Array<NexusGenRootTypes['PublicPost'] | null> | null; // [PublicPost]
    getProfileURLs: Array<string | null> | null; // [String]
    getQueuePosts: Array<NexusGenRootTypes['Post'] | null> | null; // [Post]
    getUser: NexusGenRootTypes['User'] | null; // User
    getUserByPostTitle: NexusGenRootTypes['PublicUser'] | null; // PublicUser
    getUserByUsername: NexusGenRootTypes['PublicUser'] | null; // PublicUser
    getUserThreads: Array<NexusGenRootTypes['Thread'] | null> | null; // [Thread]
    interests: NexusGenRootTypes['Interest'][]; // [Interest!]!
    post: NexusGenRootTypes['Post'] | null; // Post
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    registerUser: string; // String!
    thread: NexusGenRootTypes['Thread'] | null; // Thread
  }
  Record: { // field return type
    content: string | null; // String
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    name: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  Thread: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // String!
    messages: NexusGenRootTypes['Message'][]; // [Message!]!
    readHistory: NexusGenRootTypes['Record'][]; // [Record!]!
    repliesAllowed: boolean; // Boolean!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    users: NexusGenRootTypes['User'][]; // [User!]!
  }
  User: { // field return type
    chosenUsername: string | null; // String
    coverImage: string; // String!
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    credit: number; // Int!
    email: string; // String!
    generatedUsername: string; // String!
    name: string | null; // String
    posts: NexusGenRootTypes['Post'][]; // [Post!]!
    profileImage: string; // String!
    threads: NexusGenRootTypes['Thread'][]; // [Thread!]!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenFieldTypeNames {
  Category: { // field return type name
    id: 'String'
    interests: 'Interest'
    name: 'String'
  }
  Interest: { // field return type name
    categories: 'Category'
    generatedInterestSlug: 'String'
    id: 'String'
    name: 'String'
    posts: 'Post'
  }
  Message: { // field return type name
    content: 'String'
    createdAt: 'DateTime'
    id: 'String'
    post: 'Post'
    type: 'String'
    updatedAt: 'DateTime'
    user: 'User'
  }
  Mutation: { // field return type name
    createMessage: 'Message'
    createOneRecord: 'Record'
    createPost: 'Post'
    deletePost: 'String'
    updatePost: 'Post'
    updateProfile: 'String'
  }
  Post: { // field return type name
    content: 'String'
    contentPreview: 'String'
    contentType: 'String'
    createdAt: 'DateTime'
    creator: 'User'
    description: 'String'
    generatedTitleSlug: 'String'
    id: 'String'
    interest: 'Interest'
    title: 'String'
    updatedAt: 'DateTime'
  }
  PublicPost: { // field return type name
    content: 'String'
    contentPreview: 'String'
    contentType: 'String'
    createdAt: 'DateTime'
    description: 'String'
    generatedTitleSlug: 'String'
    id: 'String'
    interest: 'Interest'
    title: 'String'
    updatedAt: 'DateTime'
  }
  PublicUser: { // field return type name
    chosenUsername: 'String'
    coverImage: 'String'
    generatedUsername: 'String'
    name: 'String'
    profileImage: 'String'
  }
  Query: { // field return type name
    authenticate: 'String'
    categories: 'Category'
    getPostByPostTitle: 'PublicPost'
    getPostImpressions: 'Message'
    getPostURLs: 'String'
    getPostsByUsername: 'PublicPost'
    getProfileURLs: 'String'
    getQueuePosts: 'Post'
    getUser: 'User'
    getUserByPostTitle: 'PublicUser'
    getUserByUsername: 'PublicUser'
    getUserThreads: 'Thread'
    interests: 'Interest'
    post: 'Post'
    posts: 'Post'
    registerUser: 'String'
    thread: 'Thread'
  }
  Record: { // field return type name
    content: 'String'
    createdAt: 'DateTime'
    id: 'String'
    name: 'String'
    updatedAt: 'DateTime'
  }
  Thread: { // field return type name
    createdAt: 'DateTime'
    id: 'String'
    messages: 'Message'
    readHistory: 'Record'
    repliesAllowed: 'Boolean'
    updatedAt: 'DateTime'
    users: 'User'
  }
  User: { // field return type name
    chosenUsername: 'String'
    coverImage: 'String'
    createdAt: 'DateTime'
    credit: 'Int'
    email: 'String'
    generatedUsername: 'String'
    name: 'String'
    posts: 'Post'
    profileImage: 'String'
    threads: 'Thread'
    updatedAt: 'DateTime'
  }
}

export interface NexusGenArgTypes {
  Category: {
    interests: { // args
      after?: NexusGenInputs['InterestWhereUniqueInput'] | null; // InterestWhereUniqueInput
      before?: NexusGenInputs['InterestWhereUniqueInput'] | null; // InterestWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Interest: {
    categories: { // args
      after?: NexusGenInputs['CategoryWhereUniqueInput'] | null; // CategoryWhereUniqueInput
      before?: NexusGenInputs['CategoryWhereUniqueInput'] | null; // CategoryWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    posts: { // args
      after?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      before?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Mutation: {
    createMessage: { // args
      authorEmail: string; // String!
      content: string; // String!
      postCreatorEmail?: string | null; // String
      postId?: string | null; // String
      threadId?: string | null; // String
      type: string; // String!
    }
    createOneRecord: { // args
      data: NexusGenInputs['RecordCreateInput']; // RecordCreateInput!
    }
    createPost: { // args
      contentType: string; // String!
      description: string; // String!
      file1Data?: string | null; // String
      file1Name?: string | null; // String
      file1Size?: number | null; // Int
      file1Type?: string | null; // String
      file2Data?: string | null; // String
      file2Name?: string | null; // String
      file2Size?: number | null; // Int
      file2Type?: string | null; // String
      interestId: string; // String!
      text?: string | null; // String
      title: string; // String!
    }
    deletePost: { // args
      creatorId: string; // String!
      postTitleSlug: string; // String!
    }
    updatePost: { // args
      creatorId: string; // String!
      description: string; // String!
      postTitleSlug: string; // String!
      title: string; // String!
    }
    updateProfile: { // args
      coverImageData?: string | null; // String
      coverImageName?: string | null; // String
      coverImageSize?: number | null; // Int
      coverImageType?: string | null; // String
      profileImageData?: string | null; // String
      profileImageName?: string | null; // String
      profileImageSize?: number | null; // Int
      profileImageType?: string | null; // String
      userId: string; // String!
      username: string; // String!
    }
  }
  Query: {
    categories: { // args
      after?: NexusGenInputs['CategoryWhereUniqueInput'] | null; // CategoryWhereUniqueInput
      before?: NexusGenInputs['CategoryWhereUniqueInput'] | null; // CategoryWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    getPostByPostTitle: { // args
      postTitle: string; // String!
    }
    getPostImpressions: { // args
      postTitle: string; // String!
    }
    getPostsByUsername: { // args
      chosenUsername: string; // String!
    }
    getQueuePosts: { // args
      interestId?: string | null; // String
    }
    getUserByPostTitle: { // args
      postTitle: string; // String!
    }
    getUserByUsername: { // args
      chosenUsername: string; // String!
    }
    interests: { // args
      after?: NexusGenInputs['InterestWhereUniqueInput'] | null; // InterestWhereUniqueInput
      before?: NexusGenInputs['InterestWhereUniqueInput'] | null; // InterestWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    post: { // args
      where: NexusGenInputs['PostWhereUniqueInput']; // PostWhereUniqueInput!
    }
    posts: { // args
      after?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      before?: NexusGenInputs['PostWhereUniqueInput'] | null; // PostWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['PostOrderByWithRelationInput'][] | null; // [PostOrderByWithRelationInput!]
      where?: NexusGenInputs['PostWhereInput'] | null; // PostWhereInput
    }
    thread: { // args
      where: NexusGenInputs['ThreadWhereUniqueInput']; // ThreadWhereUniqueInput!
    }
  }
  Thread: {
    messages: { // args
      after?: NexusGenInputs['MessageWhereUniqueInput'] | null; // MessageWhereUniqueInput
      before?: NexusGenInputs['MessageWhereUniqueInput'] | null; // MessageWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['MessageOrderByWithRelationInput'][] | null; // [MessageOrderByWithRelationInput!]
    }
    readHistory: { // args
      after?: NexusGenInputs['RecordWhereUniqueInput'] | null; // RecordWhereUniqueInput
      before?: NexusGenInputs['RecordWhereUniqueInput'] | null; // RecordWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['RecordOrderByWithRelationInput'][] | null; // [RecordOrderByWithRelationInput!]
    }
    users: { // args
      after?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      before?: NexusGenInputs['UserWhereUniqueInput'] | null; // UserWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  User: {
    threads: { // args
      after?: NexusGenInputs['ThreadWhereUniqueInput'] | null; // ThreadWhereUniqueInput
      before?: NexusGenInputs['ThreadWhereUniqueInput'] | null; // ThreadWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenInputs['ThreadOrderByWithRelationInput'][] | null; // [ThreadOrderByWithRelationInput!]
      where?: NexusGenInputs['ThreadWhereInput'] | null; // ThreadWhereInput
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}