const impressions = [
  {
    name: "Honor",
    list: [
      { name: "Accessible" },
      { name: "Balanced" },
      { name: "Bold" },
      { name: "Brainy" },
      { name: "Brave" },
      { name: "Brawny" },
      { name: "Catchy" },
      { name: "Classy" },
      { name: "Clean" },
      { name: "Delicate" },
      { name: "Delightful" },
      { name: "Fresh" },
      { name: "Gigantic" },
      { name: "Graceful" },
      { name: "Idealistic" },
      { name: "Joyous" },
      { name: "Lavish" },
      { name: "Lean" },
      { name: "Light" },
      { name: "Lush" },
      { name: "Masterful" },
      { name: "Meaty" },
      { name: "Pleasant" },
      { name: "Powerful" },
      { name: "Profound" },
      { name: "Slim" },
      { name: "Smooth" },
      { name: "Soft" },
      { name: "Substantial" },
      { name: "Upbeat" },
      { name: "Warm" },
    ],
  },
  {
    name: "Creative",
    list: [
      { name: "Atmospheric" },
      { name: "Chic" },
      { name: "Danceable" },
      { name: "Dazzling" },
      { name: "Different" },
      { name: "Distinct" },
      { name: "Earthy" },
      { name: "Electric" },
      { name: "Elegant" },
      { name: "Exotic" },
      { name: "Futuristic" },
      { name: "Ghostly" },
      { name: "Hypnotic" },
      { name: "Imaginative" },
      { name: "Jazzy" },
      { name: "Magical" },
      { name: "Majestic" },
      { name: "Original" },
      { name: "Panoramic" },
      { name: "Retro" },
      { name: "Rustic" },
      { name: "Spicy" },
      { name: "Spooky" },
      { name: "Theatrical" },
      { name: "Tropical" },
      { name: "Watery" },
    ],
  },
  {
    name: "Intellect",
    list: [
      { name: "Brief" },
      { name: "Careful" },
      { name: "Clear" },
      { name: "Deep" },
      { name: "Dynamic" },
      { name: "Focused" },
      { name: "Functional" },
      { name: "Helpful" },
      { name: "Holistic" },
      { name: "intelligent" },
      { name: "Intricate" },
      { name: "Knowledgeable" },
      { name: "Memorable" },
      { name: "Modern" },
      { name: "Necessary" },
      { name: "Nifty" },
      { name: "Rare" },
      { name: "Scientific" },
      { name: "Sharp" },
      { name: "Simple" },
      { name: "Sophisticated" },
    ],
  },
  {
    name: "Action",
    list: [
      { name: "Adaptable" },
      { name: "Adventurous" },
      { name: "Arduous" },
      { name: "Calm" },
      { name: "Fast" },
      { name: "Handy" },
      { name: "Healthy" },
      { name: "Invincible" },
      { name: "Lively" },
      { name: "Mighty" },
      { name: "Natural" },
      { name: "Optimal" },
      { name: "Productive" },
      { name: "Ready" },
      { name: "Refreshing" },
      { name: "Robust" },
      { name: "Steady" },
      { name: "Sturdy" },
      { name: "Sunny" },
      { name: "Tested" },
      { name: "Tidy" },
      { name: "Tough" },
      { name: "Towering" },
      { name: "Tranquil" },
      { name: "Useful" },
    ],
  },
  {
    name: "Social",
    list: [
      { name: "Adorable" },
      { name: "Alluring" },
      { name: "Bittersweet" },
      { name: "Bizarre" },
      { name: "Comical" },
      { name: "Confident" },
      { name: "Cultured" },
      { name: "Discreet" },
      { name: "Encouraging" },
      { name: "Familiar" },
      { name: "Funny" },
      { name: "Harmonious" },
      { name: "Heartwarming" },
      { name: "Heavenly" },
      { name: "Hilarious" },
      { name: "Homely" },
      { name: "Mature" },
      { name: "Mysterious" },
      { name: "Neighborly" },
      { name: "Nostalgic" },
      { name: "Open" },
      { name: "Peaceful" },
      { name: "Quiet" },
      { name: "Romantic" },
      { name: "Rousing" },
      { name: "Sentimental" },
      { name: "Sincere" },
      { name: "Tasteful" },
      { name: "Tender" },
      { name: "Thoughtful" },
    ],
  },
];

export default impressions;
